<?php 
session_start();
include("../db_connect.php");
if($_SESSION['logadm']=="adm")
{

$up="UPDATE ".$pre."ustawienia SET `ust_oglp`='".htmlspecialchars($_POST['oglp'])."',`ust_chatp`='".htmlspecialchars($_POST['chatp'])."',`ust_meta_title`='".htmlspecialchars($_POST['meta_title'])."',`ust_meta_key`='".htmlspecialchars($_POST['meta_key'])."',`ust_meta_desc`='".htmlspecialchars($_POST['meta_desc'])."',`ust_pay_dod`='".htmlspecialchars($_POST['pay_dod'])."',`ust_pay_typ`='".htmlspecialchars($_POST['pay_typ'])."',`ust_pay_typ_sms`='".htmlspecialchars($_POST['pay_typ_sms'])."',`ust_meta_title`='".htmlspecialchars($_POST['meta_title'])."',`ust_meta_key`='".htmlspecialchars($_POST['meta_key'])."',`ust_meta_desc`='".htmlspecialchars($_POST['meta_desc'])."',ust_max_file_size='".htmlspecialchars($_POST['max_file_size'])."',`ust_cookie_on`='".htmlspecialchars($_POST['cookie_on'])."',`ust_wiek`='".htmlspecialchars($_POST['wiek'])."',`ust_dotpay_sms`='".htmlspecialchars($_POST['dotpay_sms'])."',`ust_18`='".htmlspecialchars($_POST['kos'])."',`ust_lang_on`='".htmlspecialchars($_POST['lang_on'])."',`ust_lang_d`='".htmlspecialchars($_POST['lang_d'])."',`ust_pin_urlc`='".htmlspecialchars($_POST['dotpay_pin'])."',`ust_typ_p`='".htmlspecialchars($_POST['typ_p'])."',`ust_ovip`='".htmlspecialchars($_POST['ovip'])."',`ust_kv`='".htmlspecialchars($_POST['ukv'])."',ust_ko='".htmlspecialchars($_POST['uko'])."',ust_in_txt='".$_POST['in_txt']."', ust_pvip='".htmlspecialchars($_POST['pvip'])."',ust_pwvip='".htmlspecialchars($_POST['pwvip'])."',ust_kvip='".htmlspecialchars($_POST['kvip'])."',ust_cenapkt='".htmlspecialchars($_POST['cenapkt'])."',ust_dotpay='".htmlspecialchars($_POST['dotpay'])."',ust_pi3='".htmlspecialchars($_POST['pi3'])."',ust_pi2='".htmlspecialchars($_POST['pi2'])."',ust_pi1='".htmlspecialchars($_POST['pi1'])."',ust_pk3='".htmlspecialchars($_POST['pk3'])."',ust_pk2='".htmlspecialchars($_POST['pk2'])."',ust_pk1='".htmlspecialchars($_POST['pk1'])."',ust_pc3='".htmlspecialchars($_POST['pc3'])."',ust_pc2='".htmlspecialchars($_POST['pc2'])."',ust_pc1='".htmlspecialchars($_POST['pc1'])."',ust_cenaf='".htmlspecialchars($_POST['cenaf'])."',ust_gift='".htmlspecialchars($_POST['gift'])."', ust_give='".htmlspecialchars($_POST['give'])."', ust_nazwa='".htmlspecialchars($_POST['nazwa'])."', ust_adres='".htmlspecialchars($_POST['adres'])."', ust_templates='".htmlspecialchars($_POST['templates'])."', `ust_cache`='".htmlspecialchars($_POST['cache'])."', `ust_edytor`='".htmlspecialchars($_POST['edytor'])."' WHERE ust_id='1'";
db_query($up);

}
header("Location: index.php?page=ustawienia&action=podstawowe&e=1#glowne");
?>